Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          NeosRulez.Comments:
            - Main
            - 'NodeTypes/*'
      defaultLanguage: 'de'
    nodeTypes:
      groups:
        comments:
          position: 'end'
          label: NeosRulez.Comments:Main:pluginname
    fusion:
      autoInclude:
        NeosRulez.Comments: true
    modules:
      neosrulezcomments:
        label: NeosRulez.Comments:Main:pluginname
        controller: '\Neos\Neos\Controller\Module\ManagementController'
        description: NeosRulez.Comments:Main:pluginname
        icon: 'icon-comments'
        resource: 'Neos_Neos_Backend_Module_Management'
        submodules:
          comments:
            label: NeosRulez.Comments:Main:allcomments
            controller: '\NeosRulez\Comments\Controller\CommentController'
            description: NeosRulez.Comments:Main:allcommentsdescription
            icon: 'icon-comment-o'
            actions:
              index:
                label: NeosRulez.Comments:Main:allcomments
                title: NeosRulez.Comments:Main:allcomments
NeosRulez:
  Comments:
    usingGravatar: true
    gravatarImgSize: '64'
    sendMails: false
    adminName: 'Admin'
    adminMail: 'mail@patriceckhart.com'
    mailSubject: 'Kommentar'